### PR TITLE
support importing from node modules

### PR DESCRIPTION
**Pull request by scarney81**
This pull request brings support for `@import 'some_node_module/some_stylus_file'` by merging any paths specified by `options` with the paths available in `modules.path`.

With this enhancement, you now have the ability to manage your shared stylus dependencies, like mixins and variables, across packages.

### CODE REVIEW

**Comment by todesignandconquer** [comment]
:+1:

**Comment by DamonOehlman** [comment]
@scarney81 Thanks for this - looks really useful.  I was just reviewing the files in the PR though and a little confused as to why the the `external/example.styl` resides in the `test` directory rather than the `node_modules/external` directory that you created?

From what you said above, I would have expected the file would have been included there (or even better in a version pinned module that does supply some stylus functionality that we can use as a test rather than a "fake" module).

**Comment by scarney81** [comment]
@DamonOehlman - `node_modules/external` is actually a symlink to the file `test/external/example.styl`. Really, I was just using this as a way to simulate a package installed via `npm` rather than actually writing and publishing an additional module (though I supposed a version pinned module would have sufficed as well). 

Let me know if you'd like me to change up how the test/symlink'd file works - I'm happy to make any modifications.

Thanks for the great package!!

**Comment by DamonOehlman** [comment]
Ah - that makes sense :)

Is there an existing package for the test that we can use?  I think it's probably a slightly better way to go and something that will also work for Windows users.

**Comment by scarney81** [comment]
So, `bootstrap` might make a good example - I'm sure more than a few folks might be looking for an example of how to integrate it.

https://www.npmjs.com/package/bootstrap-styl would be easy to integrate:

```
@require 'bootstrap-styl/bootstrap/mixins/gradients.styl'

body
  background-color gradient-horizontal()
```

**Comment by scarney81** [comment]
Also, excellent point re: windows users. The `symlink` solution is definitely less than optimal there.

**Comment by scarney81** [comment]
@DamonOehlman - here is an updated commit using `bootstrap-styl` as an external (dev) dependency: https://github.com/lanetix/stylify/commit/bd1c1827d141de8935b6eb04d13472fd1b7ac135

**Pull request closed without merging**
